/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui.dialog {
    export class QuestionDialogUI extends Dialog {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("dialog/QuestionDialog");
        }
    }
}